- name: evobeat data collector
  hosts: all
  gather_facts: no
  tasks:
    - name: Test IP and SSH connectivity
      evobeat:
        mode: 'test'
        elastic_host: 'elastic.default.192.168.10.120.nip.io'
        elastic_index: 'test-evobeat'
        elastic_username: 'evolvere'
        elastic_password: 'evolvere'
        elastic_verify_certs: False
        operation: 'reachability'
        hostip: '{{ ansible_host }}'
        hostname: '{{ inventory_hostname }}'
        username: 'admin'
        password: 'admin'
        debug: True
      register: result
      #no_log: true

    - name : Print result
      debug:
        msg: "{{ result }}"
